---
- hosts: pi-tpr
  remote_user: "${ansible_ssh_user}"
  become_method: sudo

  tasks:
#    - name: set default gw
#      become: true
#      command: route del default gw 10.250.3.1 dev eth0
    - name: ensure dhcpd is not running
      become: true
      service: name=dhcpcd state=stopped

  roles:
    - common
    - packages
    - oar
#    - security
#    - git
  environment:
    http_proxy: http://10.250.3.254:3128
