---
# file: roles/packages/tasks/main.yml

- name: update_packages_apt
  become: true
  apt: update_cache=yes upgrade=yes
#  notify:
#    - install_packages
  when: ansible_os_family == "Debian"

- name: update_packages_pacman
  become: true
  pacman: update_cache=yes upgrade=yes
  notify:
    - install_packages
    - install_ansible_and_tinyproxy
  when: ansible_os_family == "Archlinux"

- name: install_packages
  become: true
  package: name={{ item }} state=latest
  with_items:
    - tmux
    - htop
    - "{{vim}}"
    - make
    - git
    - gcc
    - nmap
    - "{{nfs}}"

- name: enable pacman colors
  become: true
  lineinfile: dest=/etc/pacman.conf regexp='^#Color$' line='Color'
  when: ansible_os_family == "Archlinux"
